// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8AFvbQGJkB9vXRyfNPXT4bdvJoaZq_c',
    appId: '1:627183800420:web:059cb48c7aad51e1d80f71',
    messagingSenderId: '627183800420',
    projectId: 'mislab2-f734f',
    authDomain: 'mislab2-f734f.firebaseapp.com',
    storageBucket: 'mislab2-f734f.firebasestorage.app',
    measurementId: 'G-F05DFKK0NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD12R_PH4GlJ71V5T-glxEQ2WTGHjSfYrc',
    appId: '1:627183800420:android:5d55646aab4e7a7bd80f71',
    messagingSenderId: '627183800420',
    projectId: 'mislab2-f734f',
    storageBucket: 'mislab2-f734f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs3Aoux_2LRYNWz-HYJVQ-24S61orCH5M',
    appId: '1:627183800420:ios:187f191dff73d82bd80f71',
    messagingSenderId: '627183800420',
    projectId: 'mislab2-f734f',
    storageBucket: 'mislab2-f734f.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs3Aoux_2LRYNWz-HYJVQ-24S61orCH5M',
    appId: '1:627183800420:ios:187f191dff73d82bd80f71',
    messagingSenderId: '627183800420',
    projectId: 'mislab2-f734f',
    storageBucket: 'mislab2-f734f.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_8AFvbQGJkB9vXRyfNPXT4bdvJoaZq_c',
    appId: '1:627183800420:web:4ae443f700ea289cd80f71',
    messagingSenderId: '627183800420',
    projectId: 'mislab2-f734f',
    authDomain: 'mislab2-f734f.firebaseapp.com',
    storageBucket: 'mislab2-f734f.firebasestorage.app',
    measurementId: 'G-047ECGWMBN',
  );
}
